//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employeewithef.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Department
    {
        public int deptid { get; set; }
        [Required(ErrorMessage = "Department name is required")]
        public string deptname { get; set; }
       
        public Nullable<int> empid { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
